# Reads ENABLE_SANITIZER_* cache variables set by CMakePresets
# Usage: target_apply_sanitizers(my_target)
function(target_apply_sanitizers target)
  set(sanitizers "")

  if(ENABLE_SANITIZER_ADDRESS)
    list(APPEND sanitizers "address")
  endif()
  if(ENABLE_SANITIZER_THREAD)
    list(APPEND sanitizers "thread")
  endif()
  if(ENABLE_SANITIZER_UNDEFINED)
    list(APPEND sanitizers "undefined")
  endif()
  if(ENABLE_SANITIZER_MEMORY)
    list(APPEND sanitizers "memory")
  endif()
  if(ENABLE_SANITIZER_LEAK)
    list(APPEND sanitizers "leak")
  endif()

  if(sanitizers)
    list(JOIN sanitizers "," sanitizer_flags)
    target_compile_options(${target} PRIVATE -fsanitize=${sanitizer_flags} -fno-omit-frame-pointer -g)
    target_link_options(${target} PRIVATE -fsanitize=${sanitizer_flags})
  endif()
endfunction()
